### ISSUE TITLE
快捷键问题

### ISSUE THREAD

**Issue by milkbing** [VideoRoll/VideoRoll#119]
打开youtube的视频后使用Ctrl+方向键无效，必须点击一下该扩展图标才可以使用快捷键。不知道是不是我的问题。

**Comment by gxy5202** [comment]
> 打开youtube的视频后使用Ctrl+方向键无效，必须点击一下该扩展图标才可以使用快捷键。不知道是不是我的问题。

确实需要先激活插件才能使用快捷键，官网https://gomi. site/VideoRoll的FAQ有说明的。这个我看看能不能优化一下吧
