### ISSUE TITLE
在 tiktok.com 会导致视频无法播放

### ISSUE THREAD

**Issue by mlkt** [VideoRoll/VideoRoll#226]
![image](https://github.com/user-attachments/assets/ebb6639d-0bf8-4e8f-a661-6f9e8586d983)
![image](https://github.com/user-attachments/assets/171b07c6-9b69-4475-a922-bd18a66f8fdc)

经排查是请求视频的URL返回403，禁用扩展后恢复正常，启用扩展后会导致请求视频URL时没有带Cookie头，原因不明

浏览器版本：Chrome 128.0.6613.114

**Comment by gxy5202** [comment]
> ![image](https://github.com/user-attachments/assets/ebb6639d-0bf8-4e8f-a661-6f9e8586d983)
> ![image](https://github.com/user-attachments/assets/171b07c6-9b69-4475-a922-bd18a66f8fdc)
> 
> 经排查是请求视频的URL返回403，禁用扩展后恢复正常，启用扩展后会导致请求视频URL时没有带Cookie头，原因不明
> 
> 浏览器版本：Chrome 128.0.6613.114

插件版本是1.1.7吗

**Comment by mlkt** [comment]
> 插件版本是1.1.7吗

是的

**Comment by gxy5202** [comment]
> > 插件版本是1.1.7吗
> 
> 是的

找到原因了，是由于给视频添加了`crossorigin`属性导致的，是为了实现截图功能

**Comment by gxy5202** [comment]
v1.1.8已修复
