### ISSUE TITLE
Cache Site Button not showing on Interface

### ISSUE THREAD

**Issue by plarindam** [VideoRoll/VideoRoll#233]
I am using this extension and I am quite happy with the performance but recently I found that the "Cache Site button" is missing from the interface. From where I can save the site settings on this extension please guide me.

**Comment by gxy5202** [comment]
> I am using this extension and I am quite happy with the performance but recently I found that the "Cache Site button" is missing from the interface. From where I can save the site settings on this extension please guide me.

![image](https://github.com/user-attachments/assets/dd8ccc81-b891-41bc-8c28-dec2e28fcc2c)
