### ISSUE TITLE
[feature]do we need reposition function?

### ISSUE THREAD

**Issue by gxy5202** [VideoRoll/VideoRoll#59]

**Comment by smith558** [comment]
Definitely. Required for the zoom functionality to be useful. I'd use a UI component similar to the existing one for the re-positioning. (see pic) There's a similar extension that already supports repositioning. (https://chrome.google.com/webstore/detail/youtube-zoom/bbafphllnkfgkcbilhekaooohoiabojh)
![image](https://user-images.githubusercontent.com/44023416/194923335-a37fa230-cd07-4bfa-965c-a529663a9887.png)

**Comment by gxy5202** [comment]
> 

Thank you for your feedback. As you say, repositioning is necessary when you are using zooming. Now we are working on this function and it will be released in the next version😉

**Comment by gxy5202** [comment]
> Definitely. Required for the zoom functionality to be useful. I'd use a UI component similar to the existing one for the re-positioning. (see pic) There's a similar extension that already supports repositioning. (https://chrome.google.com/webstore/detail/youtube-zoom/bbafphllnkfgkcbilhekaooohoiabojh) ![image](https://user-images.githubusercontent.com/44023416/194923335-a37fa230-cd07-4bfa-965c-a529663a9887.png)

Thank you for your feedback. As you say, repositioning is necessary when you are using zooming. Now we are working on this function and it will be released in the next version.

**Comment by gxy5202** [comment]
Added in the v1.1.1
