### ISSUE TITLE
youtube video does not rotate or does not fill the screen after rotation

### ISSUE THREAD

**Issue by deviljoker5200** [VideoRoll/VideoRoll#64]
youtube video does not rotate or does not fill the screen after rotation

**Comment by deviljoker5200** [comment]
some video can't

**Comment by gxy5202** [comment]
> youtube video does not rotate or does not fill the screen after rotation

well, if it's not working, try refresh the page. It's probably the same problem as this issue https://github.com/VideoRoll/VideoRoll/issues/50#issue-1358973054

The second issue probably because of the size of the video itself, then u need to use zoom function to resolve it.
